package interfaces;


/**
* interfaces/_PhoneBookClientInterfaceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from clientIDL.idl
* Quinta-feira, 16 de Outubro de 2014 17h06min47s GMT-03:00
*/

public class _PhoneBookClientInterfaceStub extends org.omg.CORBA.portable.ObjectImpl implements interfaces.PhoneBookClientInterface
{

  public void updateListContact (String listContact)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateListContact", true);
                $out.write_string (listContact);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                updateListContact (listContact        );
            } finally {
                _releaseReply ($in);
            }
  } // updateListContact

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:interfaces/PhoneBookClientInterface:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _PhoneBookClientInterfaceStub
