package interfaces;


/**
* interfaces/PhoneBookServerInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from serverIDL.idl
* Domingo, 5 de Outubro de 2014 19h41min41s BRT
*/

public abstract class PhoneBookServerInterfacePOA extends org.omg.PortableServer.Servant
 implements interfaces.PhoneBookServerInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertContact", new java.lang.Integer (0));
    _methods.put ("getListContact", new java.lang.Integer (1));
    _methods.put ("updateContactName", new java.lang.Integer (2));
    _methods.put ("updateContactNumber", new java.lang.Integer (3));
    _methods.put ("deleteContact", new java.lang.Integer (4));
    _methods.put ("getInternalClockLogic", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // interfaces/PhoneBookServerInterface/insertContact
       {
         String contactName = in.read_string ();
         int contactNumber = in.read_long ();
         this.insertContact (contactName, contactNumber);
         out = $rh.createReply();
         break;
       }

       case 1:  // interfaces/PhoneBookServerInterface/getListContact
       {
         String $result = null;
         $result = this.getListContact ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // interfaces/PhoneBookServerInterface/updateContactName
       {
         String contactNameUpdated = in.read_string ();
         String contactNameOld = in.read_string ();
         this.updateContactName (contactNameUpdated, contactNameOld);
         out = $rh.createReply();
         break;
       }

       case 3:  // interfaces/PhoneBookServerInterface/updateContactNumber
       {
         String contactName = in.read_string ();
         int contactNumberOld = in.read_long ();
         this.updateContactNumber (contactName, contactNumberOld);
         out = $rh.createReply();
         break;
       }

       case 4:  // interfaces/PhoneBookServerInterface/deleteContact
       {
         String contact = in.read_string ();
         this.deleteContact (contact);
         out = $rh.createReply();
         break;
       }

       case 5:  // interfaces/PhoneBookServerInterface/getInternalClockLogic
       {
         int $result = (int)0;
         $result = this.getInternalClockLogic ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:interfaces/PhoneBookServerInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PhoneBookServerInterface _this() 
  {
    return PhoneBookServerInterfaceHelper.narrow(
    super._this_object());
  }

  public PhoneBookServerInterface _this(org.omg.CORBA.ORB orb) 
  {
    return PhoneBookServerInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class PhoneBookServerInterfacePOA
