package interfaces;


/**
* interfaces/PhoneBookClientInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from clientIDL.idl
* Quinta-feira, 16 de Outubro de 2014 17h06min47s GMT-03:00
*/

public abstract class PhoneBookClientInterfacePOA extends org.omg.PortableServer.Servant
 implements interfaces.PhoneBookClientInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("updateListContact", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // interfaces/PhoneBookClientInterface/updateListContact
       {
         String listContact = in.read_string ();
         this.updateListContact (listContact);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:interfaces/PhoneBookClientInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PhoneBookClientInterface _this() 
  {
    return PhoneBookClientInterfaceHelper.narrow(
    super._this_object());
  }

  public PhoneBookClientInterface _this(org.omg.CORBA.ORB orb) 
  {
    return PhoneBookClientInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class PhoneBookClientInterfacePOA
