package interfaces;


/**
* interfaces/PhoneBookClientInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from clientIDL.idl
* Quinta-feira, 16 de Outubro de 2014 17h06min47s GMT-03:00
*/

public interface PhoneBookClientInterface extends PhoneBookClientInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PhoneBookClientInterface
