package interfaces;


/**
* interfaces/PhoneBookServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from serverIDL.idl
* Domingo, 5 de Outubro de 2014 19h41min41s BRT
*/

public interface PhoneBookServerInterfaceOperations 
{
  void insertContact (String contactName, int contactNumber);
  String getListContact ();
  void updateContactName (String contactNameUpdated, String contactNameOld);
  void updateContactNumber (String contactName, int contactNumberOld);
  void deleteContact (String contact);
  int getInternalClockLogic ();
} // interface PhoneBookServerInterfaceOperations
