package interfaces;


/**
* interfaces/PhoneBookClientInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from clientIDL.idl
* Quinta-feira, 16 de Outubro de 2014 17h06min47s GMT-03:00
*/

public interface PhoneBookClientInterfaceOperations 
{
  void updateListContact (String listContact);
} // interface PhoneBookClientInterfaceOperations
