package interfaces;


/**
* interfaces/PhoneBookServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from serverIDL.idl
* Domingo, 5 de Outubro de 2014 19h41min41s BRT
*/

public interface PhoneBookServerInterface extends PhoneBookServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PhoneBookServerInterface
