package interfaces;


/**
* interfaces/PhoneBookServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from serverIDL.idl
* Quinta-feira, 2 de Outubro de 2014 00h54min42s BRT
*/

public interface PhoneBookServerInterface extends PhoneBookServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PhoneBookServerInterface
